[project]
name = "ArtistsForArtists"
dependencies = [
    "flask",
    "flask-login",
	"flask-talisman",
    "pandoc",
    "pypandoc",
    "Flask-WTF",
]
version = "1.1.00"
authors = [
    {name = "Jacob Jirak"}
]
description = "A CMS designed by authors for authors."

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"